name: Red Hat Dependency Analytics (RHDA)
description: Analyze vulnerabilities in application dependencies
author: Red Hat
branding:
  icon: circle
  color: red

inputs:
  manifest_file_path:
    description: Path to target manifest file for analysis.
    required: false
  rhda_report_name:
    description: Name of the file where the Red Hat Dependency Analytics report will be saved.
    required: false
    default: redhat-dependency-analytics-report
  snyk_token:
    description: Snyk token to be used to authenticate to the Red Hat Dependency Analytics.
    required: false
  set_python_virtual_environment:
    description: Automates the installation of missing packages in a Python virtual environment when set to true.
    required: false
  match_manifest_version:
    description: Restricts RHDA from performing analysis on dependency tags that do not match the tags requested within the manifest files.
    required: true
  github_token:
    description: Github token to upload SARIF file to the GitHub
    required: false
    default: ${{ github.token }}
  upload_sarif:
    description: |
      Upload the generated SARIF file, by default it is set to "true".
      If you don't want to upload SARIF file set this input to "false"
    required: false
    default: "true"
  upload_artifact:
    description: |
      Upload the generated RHDA report JSON file as an artifact.
    required: false
    default: "true"
  artifact_filename:
    description: |
      File name of the artifact to upload.
      By default it is named as 'redhat-dependency-analytics-report'
    required: false
    default: "redhat-dependency-analytics-report"
  mvn_executable_path:
    description: Specifies absolute path of mvn executable.
    required: false
    default: mvn
  npm_executable_path:
    description: Specifies absolute path of npm executable.
    required: false
    default: npm
  go_executable_path:
    description: Specifies absolute path of go executable.
    required: false
    default: go
  python3_executable_path:
    description: Specifies absolute path of python3 executable, python3 takes precedence over python.
    required: false
    default: python3
  pip3_executable_path:
    description: Specifies absolute path of pip3 executable, pip3 takes precedence over pip.
    required: false
    default: pip3
  python_executable_path:
    description: Specifies absolute path of python executable, python3 takes precedence over python.
    required: false
    default: python
  pip_executable_path:
    description: Specifies absolute path of pip executable, pip3 takes precedence over pip.
    required: false
    default: pip

outputs:
  rhda_report_json:
    description: Generated Red Hat Dependency Analytics Report in JSON format
  rhda_report_sarif:
    description: Generated Red Hat Dependency Analytics Report in SARIF format
  artifact_id:
    description: Name of the uploaded artifact

runs:
  using: 'node20'
  main: 'dist/src/index.js'
